### ISSUE TITLE
WTV020SD Spec - 32Ohm 0.25W Speakers

### ISSUE THREAD

**Issue by dsirov** [IoT-Experiments/iot-audio-player#1]
Regarding your artice: https://www.iot-experiments.com/audio-player-1-concept-and-first-circuit.
You mentioned that the spec for WTV020SD stated support for 8Ohm, 16Ohm and 32Ohm speakers.

The datasheet I can find on the Web does not mention anything at all about speakers.
Can you please point me to the datasheet you have?

Thanks in advance!

**Comment by jeanmatthieud** [comment]
Hi,

I'm sorry, but I don't have the datasheet anymore.
